version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - '7474:7474' # Neo4j Browser
      - '7687:7687' # Bolt protocol for connecting to the database
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    healthcheck:
      test: ['CMD', 'cypher-shell', '-u', 'neo4j', '-p', 'password', 'RETURN 1']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  app:
    image: kopfmann/graphql-server # Replace with the actual image name
    container_name: graphql-app
    ports:
      - '4000:4000' # The GraphQL API and Apollo Studio
    depends_on:
      neo4j:
        condition: service_healthy # Wait until Neo4j is healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./config:/usr/src/app/config
    networks:
      - app_network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  app_network:
